// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmg1BSTJ4WmPdsjCuhxa5CF4MUS3szMLU',
    appId: '1:673014649756:web:85ba122f01a4b00111ae59',
    messagingSenderId: '673014649756',
    projectId: 'e-commerce-8ebee',
    authDomain: 'e-commerce-8ebee.firebaseapp.com',
    storageBucket: 'e-commerce-8ebee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34K5Elyj1SCucIyN9XADp7gj5n6uyNy4',
    appId: '1:673014649756:android:59dc9c702eca3fba11ae59',
    messagingSenderId: '673014649756',
    projectId: 'e-commerce-8ebee',
    storageBucket: 'e-commerce-8ebee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCts5Bnmm3s-00YOQBqz5e6KeMEBQteaRU',
    appId: '1:673014649756:ios:07f6513ee5bef51111ae59',
    messagingSenderId: '673014649756',
    projectId: 'e-commerce-8ebee',
    storageBucket: 'e-commerce-8ebee.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );
}
